// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

let dbUrl = process.env["DATABASE_URL"];
if (!dbUrl && process.env.SQL_USER && process.env.SQL_HOST) {
  const host = encodeURIComponent(process.env.SQL_HOST);
  const user = encodeURIComponent(process.env.SQL_USER);
  const pass = encodeURIComponent(process.env.SQL_PASSWORD || '');
  dbUrl = `postgresql://${user}:${pass}@localhost/${process.env.SQL_DB_NAME}?host=${host}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
